server:
  port: 8081
  # port: 8084
  # port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: huesped-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios
    username: root
    password: 123456
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # ==============================================
  # Punto de entrada para los clientes (MICROSERVICIOS)
  # ==============================================
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/proyecto01-microservicios-realm

eureka:
  instance:
    prefer-ip-address: true
    # instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Configuracion que expone informacion detallada del estado de salud de la aplicacion
management:
  health:
    circuitbreakers:
      enabled: true           # Activa indicadores de salud para circuit breakers
  endpoints:
    web:
      exposure:
        include: health         # Expone solo el endpoint /actuator/health
  endpoint:
    health:
      show-details: always    # Muestra detalles completos del health check

# Configuracion de Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      huespedServiceBreaker:             # Nombre del circuito
        registerHealthIndicator: true    # Registra en /actuator/health
        eventConsumerBufferSize: 10      # Tamaño buffer de eventos
        failureRateThreshold: 50         # % fallos para abrir circuito (50%)
        minimumNumberOfCalls: 5          # Mínimo llamadas para calcular tasa
        automaticTransitionFromOpenToHalfOpenEnabled: true  # Paso automático a Half-Open
        waitDurationInOpenState: 6s      # Tiempo en OPEN antes de Half-Open
        permittedNumberOfCallsInHalfOpenState: 3  # Llamadas permitidas en Half-Open
        slidingWindowSize: 10            # Tamaño ventana deslizante (10 llamadas)
        slidingWindowType: COUNT_BASED   # Tipo: cuenta de llamadas (no tiempo)

  # Configuracion de Retry
  retry:
    instances:
      huespedServiceRetry: # Nombre del retry (debe coincidir con @Retry)
        max-attempts: 3    # Número máximo de intentos
        wait-duration: 5s  # Tiempo de espera entre cada reintento